FROM ubuntu:19.10

RUN apt update && apt autoremove \
    && apt -y install sudo curl dirmngr apt-transport-https lsb-release ca-certificates \
    && curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash - \
    && sudo apt -y install nodejs \
    && apt-get -y install git \
    && apt-get -y install subversion \
    && apt-get install -y cron \
    && apt-get install -y vim \
    && npm install ect \
    && npm install express \
    && npm install body-parser \
    && npm install md5


#FROM ubuntu:19.10

#RUN apt update && apt autoremove
#RUN apt -y install sudo curl dirmngr apt-transport-https lsb-release ca-certificates
#RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
#RUN sudo apt -y install nodejs
#RUN apt-get -y install git
#RUN apt-get install -y cron
#RUN apt-get install -y vim

#RUN npm install ect
#RUN npm install express
#RUN npm install body-parser
#RUN npm install md5

COPY _entrypoint.sh /var/_entrypoint.sh
RUN (crontab -l ; echo "* * * * * sh /var/_localApp/cronjob/minute_cron.sh >> /var/_localAppData/cron.log") | crontab

ENTRYPOINT cron start && cd /var && sh _entrypoint.sh
