FROM ubuntu:18.04

RUN apt update && apt autoremove
RUN apt -y install sudo curl dirmngr apt-transport-https lsb-release ca-certificates
RUN curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
RUN sudo apt -y install nodejs
RUN apt-get -y install git
RUN apt-get install -y cron
RUN apt-get install -y vim

RUN npm install morgan
RUN npm install debug
RUN npm install ect
RUN npm install express
RUN npm install body-parser
RUN npm install md5
RUN npm install request

ENTRYPOINT cron start && cd /var && sh _entrypoint.sh
